create_ip -vlnv xilinx.com:ip:clk_wiz:5.4 -module_name clock0
set_property -name CONFIG.PRIMITIVE -value {MMCM} -objects [get_ips clock0]
set_property -name CONFIG.PRIM_IN_FREQ -value {100.000} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT1_USED -value {true} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT2_USED -value {true} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT3_USED -value {true} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT1_REQUESTED_OUT_FREQ -value {10.000} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT2_REQUESTED_OUT_FREQ -value {25.000} -objects [get_ips clock0]
set_property -name CONFIG.CLKOUT3_REQUESTED_OUT_FREQ -value {160.000} -objects [get_ips clock0]
set_property -name CONFIG.USE_LOCKED -value {false} -objects [get_ips clock0]
set_property -name CONFIG.USE_RESET -value {false} -objects [get_ips clock0]
set_property -name CONFIG.PRIM_SOURCE -value {Single_ended_clock_capable_pin} -objects [get_ips clock0]
set_property -name CONFIG.USE_POWER_DOWN -value {false} -objects [get_ips clock0]
set_property -name generate_synth_checkpoint -value false -objects [get_files clock0.xci]